import { ArrowRight, CheckCircle2, FileSearch, Fingerprint, LockKeyhole } from "lucide-react";
import { Link } from "react-router-dom";
import { Button, Card } from "../components/ui";

export function Accueil() {
  return <div className="min-h-screen bg-sand text-ink">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6"><div className="font-display text-2xl font-bold text-forest-900">Plagiat<span className="text-coral">·FR</span></div><div className="flex gap-2"><Link to="/connexion"><Button variant="ghost">Connexion</Button></Link><Link to="/inscription"><Button>Créer un compte</Button></Link></div></nav>
    <main className="mx-auto max-w-7xl px-5 pb-20 pt-12 lg:pt-24">
      <div className="grid items-center gap-16 lg:grid-cols-[1.08fr_.92fr]">
        <section><div className="mb-6 inline-flex rounded-full bg-forest-100 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-forest-700">La confiance, documentée</div><h1 className="max-w-3xl font-display text-5xl font-semibold leading-[1.03] text-forest-900 md:text-7xl">Vérifiez l’originalité. <span className="italic text-coral">Préservez</span> l’intégrité.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-black/60">Une plateforme française d’analyse de similitudes et de détection de rédaction assistée par IA, conçue pour les établissements, formateurs et équipes éditoriales.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/inscription"><Button className="px-6">Demander un accès <ArrowRight size={18}/></Button></Link><a href="#fonctionnalites"><Button variant="secondary">Découvrir la plateforme</Button></a></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-black/55">{["PDF et DOCX", "Rapports détaillés", "Données privées"].map(x => <span className="flex items-center gap-2" key={x}><CheckCircle2 size={17} className="text-forest-500"/>{x}</span>)}</div></section>
        <Card className="relative overflow-hidden bg-forest-900 p-7 text-white"><div className="absolute right-[-50px] top-[-40px] h-48 w-48 rounded-full bg-[#e9b949]/20 blur-2xl"/><div className="relative"><p className="text-sm text-white/60">Rapport d’originalité</p><h2 className="mt-2 font-display text-3xl">Mémoire_final.pdf</h2><div className="my-8 flex items-end justify-between"><div><p className="text-6xl font-semibold">92<span className="text-2xl text-white/55">%</span></p><p className="mt-2 text-sm text-white/60">Indice d’originalité</p></div><div className="h-24 w-24 rounded-full border-[10px] border-[#e9b949] border-r-white/10" /></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white/55">Similitudes</p><p className="mt-1 text-xl font-bold">8 %</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs text-white/55">Écriture IA</p><p className="mt-1 text-xl font-bold">Faible</p></div></div></div></Card>
      </div>
      <section id="fonctionnalites" className="mt-28 grid gap-5 md:grid-cols-3">{[[FileSearch,"Analyse croisée","Repérez les passages similaires et leurs sources avec un niveau de confiance explicite."],[Fingerprint,"Détection IA responsable","Obtenez des indicateurs linguistiques expliqués, jamais présentés comme une preuve absolue."],[LockKeyhole,"Confidentialité intégrée","Fichiers privés, accès isolés par utilisateur et suppression maîtrisée des documents."]].map(([Icon,t,d]) => <Card className="p-7" key={String(t)}><Icon className="mb-5 text-coral" size={28}/><h3 className="font-display text-2xl text-forest-900">{String(t)}</h3><p className="mt-3 leading-7 text-black/55">{String(d)}</p></Card>)}</section>
    </main>
  </div>;
}
