import { Check, FileText, Loader2, LockKeyhole, UploadCloud, X } from "lucide-react";
import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button, Card } from "../components/ui";
import { useAuth } from "../contexts/AuthContext";
import { supabase, supabaseConfigured } from "../lib/supabase";
import { validerDocument } from "../lib/validation";
export function NouvelleAnalyse() {
  const { user } = useAuth(); const navigate=useNavigate(); const input=useRef<HTMLInputElement>(null);
  const [fichier,setFichier]=useState<File|null>(null); const [erreur,setErreur]=useState(""); const [chargement,setChargement]=useState(false); const [glisse,setGlisse]=useState(false);
  const choisir=(file?:File)=>{setErreur("");if(!file)return;const validation=validerDocument(file);if(validation){setErreur(validation);return}setFichier(file)};
  const lancer=async()=>{if(!fichier||!user)return;if(!supabaseConfigured){setErreur("La configuration Supabase est absente.");return}setChargement(true);setErreur("");const chemin=`${user.id}/${crypto.randomUUID()}/${fichier.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:uploadError}=await supabase.storage.from("documents").upload(chemin,fichier,{contentType:fichier.type,upsert:false});if(uploadError){setErreur("Le téléversement sécurisé a échoué. Réessayez.");setChargement(false);return}const {data,error}=await supabase.from("analyses").insert({utilisateur_id:user.id,nom_fichier:fichier.name,chemin_stockage:chemin,type_mime:fichier.type,taille_octets:fichier.size,statut:"en_attente"}).select("id").single();if(error){await supabase.storage.from("documents").remove([chemin]);setErreur("Impossible de créer l’analyse.");setChargement(false);return}await supabase.functions.invoke("analyser-document",{body:{analyse_id:data.id}});navigate(`/app/rapport/${data.id}`)};
  return <div className="mx-auto max-w-4xl p-5 lg:p-10"><p className="text-sm text-black/45">Analyse documentaire</p><h1 className="mt-1 font-display text-4xl text-forest-900">Vérifier un document</h1><p className="mt-3 max-w-2xl text-black/50">Importez un document pour lancer simultanément la recherche de similitudes et l’estimation de rédaction assistée par IA.</p><Card className="mt-8 p-5 md:p-8"><div onDragOver={e=>{e.preventDefault();setGlisse(true)}} onDragLeave={()=>setGlisse(false)} onDrop={e=>{e.preventDefault();setGlisse(false);choisir(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()} className={`grid cursor-pointer place-items-center rounded-2xl border-2 border-dashed p-10 text-center transition ${glisse?"border-forest-500 bg-forest-50":"border-black/15 hover:border-forest-500 hover:bg-forest-50/40"}`} role="button" tabIndex={0} onKeyDown={e=>e.key==="Enter"&&input.current?.click()}><input ref={input} className="hidden" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>choisir(e.target.files?.[0])}/><div className="mb-4 rounded-2xl bg-forest-100 p-4 text-forest-700"><UploadCloud size={29}/></div><h2 className="font-semibold">Déposez votre fichier ici</h2><p className="mt-2 text-sm text-black/45">ou cliquez pour parcourir · PDF ou DOCX · 20 Mo maximum</p></div>
    {fichier&&<div className="mt-4 flex items-center gap-3 rounded-xl bg-sand p-4"><FileText className="text-forest-700"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{fichier.name}</p><p className="text-xs text-black/40">{(fichier.size/1024/1024).toFixed(2)} Mo</p></div><button aria-label="Retirer le fichier" onClick={()=>setFichier(null)}><X size={18}/></button></div>}{erreur&&<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{erreur}</div>}<div className="mt-6 grid gap-3 text-sm md:grid-cols-3">{["Recherche de similitudes","Détection d’écriture IA","Rapport PDF détaillé"].map(x=><div className="flex gap-2" key={x}><Check size={17} className="text-forest-500"/>{x}</div>)}</div><Button className="mt-7 w-full" disabled={!fichier||chargement} onClick={()=>void lancer()}>{chargement?<><Loader2 className="animate-spin" size={18}/>Analyse en cours…</>:<><LockKeyhole size={17}/>Lancer l’analyse sécurisée</>}</Button></Card></div>;
}
